# 管理员
admins:
  - 269077688

# 缓存存放目录
cache_dir: ./data/


# 触发的命令
comm:
  # 查询一个公会排行  可以是公会名字 可以是排名
  keyword: ["[会公工][战会][排查][行名询]"]

  # 锁定一个公会 可以直接使用会战排行查询或者每个设定的时间推送
  locked: ["[会公工][战会][锁绑]定"]
  # 解锁一个公会
  unlocked: ["[会公工][战会]解[锁除绑]"]
  #
  defaultLucked: ["[会公工][战会][排查][行名询]$"]

#规则
rules:
  # 是否只允许管理员锁定或解锁公会
  only_admin_can_locked: True

  # 是否每个群只能绑定一个公会
  only_one_locked: false

  # 对锁定的公会多长时间更新广播一次 单位小时
  lock_clan_cron_time: 4

  # 档线多久更新一次 一般就比更新公会提前2分钟 单位分钟
  lock_clan_line_cron_time: 58

  # 获取数据的服务器地址
  base_url: https://service-kjcbcnmw-1254119946.gz.apigw.tencentcs.com
  # 获取数据的请求头
  headers:
    Content-Type: application/json
    Referer: https://kengxxiao.github.io/Kyouka/
    Custom-Source: erinilis